export const authConstant = {
  USER_REGISTER: "USER_REGISTER",
  USER_REGISTER_FAILED: "USER_REGISTER_FAILED",
  GET_USER_PROFILE: "GET_USER_PROFILE",
  GET_USER_PROFILE_FAILED: "GET_USER_PROFILE_FAILED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
};
